version: "3.8"

services:
  lndk:
    image: alex71btc/lndk:amountless-fix-v2@sha256:dcace5e9c90c4dfe26c85979f373ecebfafdf0a56b494e22fd5abe7fb731987e
    container_name: lndk
    restart: unless-stopped

    command: >
      lndk
      --address=https://YOUR_NODE_IP:10009
      --cert-path=/secrets/tls.cert
      --macaroon-path=/secrets/admin.macaroon
      --data-dir=/data
      --grpc-host=0.0.0.0
      --grpc-port=7000

    volumes:
      - lndk_data:/data
      - /root/lndk-secrets:/secrets:ro

    ports:
      - "7000:7000"

volumes:
  lndk_data:
