version: "3.8"

services:
  lndk:
    image: alex71btc/lndk:amountless-fix@sha256:f7a237a131f4b1950e7650692954db865b42ec492348936726871f65b1c1d2e3
    container_name: lndk
    restart: unless-stopped

    command: >
      lndk
      --address=https://YOUR_NODE_IP:10009
      --cert-path=/secrets/tls.cert
      --macaroon-path=/secrets/admin.macaroon
      --data-dir=/data
      --grpc-host=0.0.0.0
      --grpc-port=7000

    volumes:
      - lndk_data:/data
      - /root/lndk-secrets:/secrets:ro

    ports:
      - "7000:7000"

volumes:
  lndk_data:
