version: "3.8"

services:
  lndk:
    image: alex71btc/lndk:v0.3.0
    container_name: lndk
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
    command:
      - "sleep 120 && exec lndk --address=https://YOUR_NODE_IP:10009 --cert-path=/secrets/tls.cert --macaroon-path=/secrets/admin.macaroon --data-dir=/data --grpc-host=0.0.0.0 --grpc-port=7000"
    ports:
      - "7000:7000"
    volumes:
      - lndk_lndk_data:/data
      - lndk_secrets:/secrets:ro

volumes:
  lndk_lndk_data:
    external: true
  lndk_secrets:
    external: true

